"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SCRIPTS = [
    {
        id: 1, name: 'Script One', script: "CREATE TABLE [dbo].[Author] (\n\t[AuthorId] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_Author PRIMARY KEY,\n\t[FirstName] [nvarchar](256) NULL,\n\t[LastName] [nvarchar](256) NOT NULL,\n\t[Birthday] [datetime] NULL )\n\t\nCREATE TABLE [dbo].[Post] (\n\t[PostId] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT PK_Post PRIMARY KEY,\n\t[Title] [NVARCHAR](256) NOT NULL,\n\t[Body] [NVARCHAR](MAX) NOT NULL,\n\t[AuthorId] [INT] NOT NULL)\n\nALTER TABLE [dbo].[Post] \nADD [CreationDateTime] [DATETIME] NOT NULL DEFAULT(GETDATE())\n\n \nINSERT INTO [Author]([FirstName], [LastName], [Birthday])\nVALUES( 'Ivan', 'Ivanov', '1990-02-03' )\n\nINSERT INTO [Author]([FirstName], [LastName], [Birthday])\nVALUES( 'Adriel', 'Perez', '1990-02-03' ), ( 'Eric', 'Miller', '1998-11-13' )\n\nINSERT INTO [Post]([Title], [Body], [AuthorId])\nVALUES('SQL Introduction', 'Some text about SQL', 1)\n\nINSERT INTO [Post]([Title], [Body], [AuthorId])\nVALUES('SELECT Syntax', 'Some text about SELECT Syntax', 1)\n\n\nUPDATE [Post] \nSET [CreationDateTime] = GETDATE()\nWHERE Title = 'SQL Introduction'\n\nDELETE FROM [Author]"
    },
    {
        id: 2, name: 'Script Two', script: "CREATE TABLE [dbo].[Author] (\n\t[AuthorId] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_Author PRIMARY KEY,\n\t[FirstName] [nvarchar](256) NULL,\n\t[LastName] [nvarchar](256) NOT NULL,\n\t[Birthday] [datetime] NULL )\n\t\nCREATE TABLE [dbo].[Post] (\n\t[PostId] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT PK_Post PRIMARY KEY,\n\t[Title] [NVARCHAR](256) NOT NULL,\n\t[Body] [NVARCHAR](MAX) NOT NULL,\n\t[AuthorId] [INT] NOT NULL)\n\nALTER TABLE [dbo].[Post] \nADD [CreationDateTime] [DATETIME] NOT NULL DEFAULT(GETDATE())\n\n \nINSERT INTO [Author]([FirstName], [LastName], [Birthday])\nVALUES( 'Ivan', 'Ivanov', '1990-02-03' )\n\nINSERT INTO [Author]([FirstName], [LastName], [Birthday])\nVALUES( 'Adriel', 'Perez', '1990-02-03' ), ( 'Eric', 'Miller', '1998-11-13' )\n\nINSERT INTO [Post]([Title], [Body], [AuthorId])\nVALUES('SQL Introduction', 'Some text about SQL', 1)\n\nINSERT INTO [Post]([Title], [Body], [AuthorId])\nVALUES('SELECT Syntax', 'Some text about SELECT Syntax', 1)\n\n\nUPDATE [Post] \nSET [CreationDateTime] = GETDATE()\nWHERE Title = 'SQL Introduction'\n\nDELETE FROM [Author]"
    },
    {
        id: 3, name: 'Script End', script: "CREATE TABLE [dbo].[Author] (\n\t[AuthorId] [int] IDENTITY(1,1) NOT NULL CONSTRAINT PK_Author PRIMARY KEY,\n\t[FirstName] [nvarchar](256) NULL,\n\t[LastName] [nvarchar](256) NOT NULL,\n\t[Birthday] [datetime] NULL )\n\t\nCREATE TABLE [dbo].[Post] (\n\t[PostId] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT PK_Post PRIMARY KEY,\n\t[Title] [NVARCHAR](256) NOT NULL,\n\t[Body] [NVARCHAR](MAX) NOT NULL,\n\t[AuthorId] [INT] NOT NULL)\n\nALTER TABLE [dbo].[Post] \nADD [CreationDateTime] [DATETIME] NOT NULL DEFAULT(GETDATE())\n\n \nINSERT INTO [Author]([FirstName], [LastName], [Birthday])\nVALUES( 'Ivan', 'Ivanov', '1990-02-03' )\n\nINSERT INTO [Author]([FirstName], [LastName], [Birthday])\nVALUES( 'Adriel', 'Perez', '1990-02-03' ), ( 'Eric', 'Miller', '1998-11-13' )\n\nINSERT INTO [Post]([Title], [Body], [AuthorId])\nVALUES('SQL Introduction', 'Some text about SQL', 1)\n\nINSERT INTO [Post]([Title], [Body], [AuthorId])\nVALUES('SELECT Syntax', 'Some text about SELECT Syntax', 1)\n\n\nUPDATE [Post] \nSET [CreationDateTime] = GETDATE()\nWHERE Title = 'SQL Introduction'\n\nDELETE FROM [Author]"
    }
];
//# sourceMappingURL=mock-scripts.js.map